name: Build and Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Commit and push
        run: |
          git config --global user.name 'Dominique'
          git config --global user.email 'dominique@dulcetdash.com'
          git add build/ -f
          git commit -m "Deploying build"
          git push
